---
abstract: 'Validate PGXN distribution metadata structures'
author:
  - unknown
build_requires:
  Module::Build: 0.30
  Test::More: 0.88
configure_requires:
  Module::Build: 0.30
dynamic_config: 1
generated_by: 'Module::Build version 0.4005, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PGXN-Meta-Validator
provides:
  PGXN::Meta::Validator:
    file: lib/PGXN/Meta/Validator.pm
    version: v0.16.0
recommends:
  Test::Pod: 1.41
  Test::Pod::Coverage: 1.06
requires:
  Carp: 0
  Getopt::Long: 0
  JSON: 0
  Pod::Usage: 0
  SemVer: 0.005000
  perl: 5.01
resources:
  bugtracker: http://github.com/pgxn/pgxn-meta-validator/issues/
  homepage: http://search.cpan.org/dist/PGXN-Meta-Validator/
  license: http://dev.perl.org/licenses/
  repository: http://github.com/pgxn/pgxn-meta-validator/tree/
version: v0.16.0
